spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: create
    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      port: 6379
      host: localhost
  jwt:
    secret: ZGF5b25lLXNwcmluZz1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkK
scheduler:
  scrap:
    yahoo: "0 0 0 * * *"